input {
  file {
    path => "/data/responses.ndjson"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json_lines
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "responses-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}